---
title: "Analyzing the litter diallel"
author:
- name: "Paul L. Maurizio"
  affiliation: 
  - The University of Chicago, Department of Medicine, Chicago, IL, USA
  - The University of North Carolina at Chapel Hill, Department of Genetics, Chapel Hill, NC, USA (previous)

date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyzing the litter diallel}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  \usepackage[utf8]{inputenc}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Load packages

```{r, message=FALSE}
library("MCMCglmm")
library("litterDiallel")
library("PLMcctools")
library("xtable")
```

## Load data, add column

```{r, message=FALSE}
data("litters")
litters$inbred <- ifelse(litters$Dam_Founder == litters$Sire_Founder, 1, 0)
```

## Generate design matrices

```{r, message=FALSE}
matrices <- diallelMatrixMaker(data=litters, dam.col.name="Dam_Founder",
                               sire.col.name="Sire_Founder", batch.col.name="YearMonth",
                               batch.1.col.name="litterorder")
M.matrices <- matrices[[1]]
t.matrices <- matrices[[2]]
```
